### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by buptlj** [Li-Chongyi/Zero-DCE#20]
hi, thanks for your great work. I have a problem when i run lowlight_test.py.
`
data/test_data/DICM/32.jpg
0.001220703125
data/test_data/LIME/6.bmp
0.0012459754943847656
data/test_data/LIME/8.bmp
0.0011720657348632812
data/test_data/LIME/4.bmp
0.0012981891632080078
data/test_data/LIME/7.bmp
0.0016331672668457031
data/test_data/LIME/1.bmp
0.0012412071228027344
data/test_data/LIME/2.bmp
0.0011746883392333984
data/test_data/LIME/9.bmp
0.0011982917785644531
data/test_data/LIME/5.bmp
Traceback (most recent call last):
  File "lowlight_test.py", line 63, in <module>
    lowlight(image)
  File "lowlight_test.py", line 35, in lowlight
    _,enhanced_image,_ = DCE_net(data_lowlight)
  File "/home/mi/anaconda3/envs/zero-dce/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mi/workspace/projects/low-light-enhancement/Zero-DCE/Zero-DCE_code/model.py", line 37, in forward
    x4 = self.relu(self.e_conv4(x3))
  File "/home/mi/anaconda3/envs/zero-dce/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mi/anaconda3/envs/zero-dce/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/home/mi/anaconda3/envs/zero-dce/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 368.00 MiB

`

**Comment by buptlj** [comment]
找到原因了，是data/test_data/LIME/5.bmp这张图片太大了，我测试机器显存2G。

**Comment by frensher** [comment]
为什么我300*300的图片都会报错
